### ISSUE TITLE
Possibility to have more actions

### ISSUE THREAD

**Issue by newhen** [manwhoami/FindMyiPhone#6]
Like for instance tell the iphones to beep because they are lost?

**Comment by manwhoami** [comment]
The problem with this is that the user gets an email notification when the action is performed. 

That being said, this is a good idea that I can get working on, it shouldn't be too much tweaking. I will also add some code to have the user of the script verify if they want to perform an action that will send the iCloud user a notification.

**Comment by tomballgithub** [comment]
I have been trying to make the playSound action work (with message) but cannot.  I keep getting an HTML Error 500 returned

**Comment by manwhoami** [comment]
I have added this feature along with lat/long street address resolution, and better formatting. Check the latest commit for these.

**Comment by tomballgithub** [comment]
Sound playing works great, thank you!
